'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FTService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="FTService.SettingServiceSoap")>  _
    Public Interface SettingServiceSoap
        
        'CODEGEN: Generating message contract since element name testerType from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetMailBoxPath", ReplyAction:="*")>  _
        Function GetMailBoxPath(ByVal request As FTService.GetMailBoxPathRequest) As FTService.GetMailBoxPathResponse
        
        'CODEGEN: Generating message contract since element name flowName from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTestFlowNo", ReplyAction:="*")>  _
        Function GetTestFlowNo(ByVal request As FTService.GetTestFlowNoRequest) As FTService.GetTestFlowNoResponse
        
        'CODEGEN: Generating message contract since element name errorNo from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LotRptIsIgnore", ReplyAction:="*")>  _
        Function LotRptIsIgnore(ByVal request As FTService.LotRptIsIgnoreRequest) As FTService.LotRptIsIgnoreResponse
        
        'CODEGEN: Generating message contract since element name testerType from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTesterMailBoxPath", ReplyAction:="*")>  _
        Function GetTesterMailBoxPath(ByVal request As FTService.GetTesterMailBoxPathRequest) As FTService.GetTesterMailBoxPathResponse
        
        'CODEGEN: Generating message contract since element name QRTester from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTesterMailBoxPathWithPrefix", ReplyAction:="*")>  _
        Function GetTesterMailBoxPathWithPrefix(ByVal request As FTService.GetTesterMailBoxPathWithPrefixRequest) As FTService.GetTesterMailBoxPathWithPrefixResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetMailBoxPathRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetMailBoxPath", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.GetMailBoxPathRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.GetMailBoxPathRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetMailBoxPathRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public testerType As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal testerType As String)
            MyBase.New
            Me.testerType = testerType
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetMailBoxPathResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetMailBoxPathResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.GetMailBoxPathResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.GetMailBoxPathResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetMailBoxPathResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetMailBoxPathResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetMailBoxPathResult As String)
            MyBase.New
            Me.GetMailBoxPathResult = GetMailBoxPathResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTestFlowNoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTestFlowNo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.GetTestFlowNoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.GetTestFlowNoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTestFlowNoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public flowName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal flowName As String)
            MyBase.New
            Me.flowName = flowName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTestFlowNoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTestFlowNoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.GetTestFlowNoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.GetTestFlowNoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTestFlowNoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetTestFlowNoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTestFlowNoResult As String)
            MyBase.New
            Me.GetTestFlowNoResult = GetTestFlowNoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LotRptIsIgnoreRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LotRptIsIgnore", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.LotRptIsIgnoreRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.LotRptIsIgnoreRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LotRptIsIgnoreRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public errorNo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal errorNo As String)
            MyBase.New
            Me.errorNo = errorNo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LotRptIsIgnoreResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LotRptIsIgnoreResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.LotRptIsIgnoreResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.LotRptIsIgnoreResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LotRptIsIgnoreResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public LotRptIsIgnoreResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LotRptIsIgnoreResult As Boolean)
            MyBase.New
            Me.LotRptIsIgnoreResult = LotRptIsIgnoreResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTesterMailBoxPathRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTesterMailBoxPath", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.GetTesterMailBoxPathRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.GetTesterMailBoxPathRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTesterMailBoxPathRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public testerType As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public testerNo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal testerType As String, ByVal testerNo As String)
            MyBase.New
            Me.testerType = testerType
            Me.testerNo = testerNo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTesterMailBoxPathResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTesterMailBoxPathResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.GetTesterMailBoxPathResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.GetTesterMailBoxPathResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTesterMailBoxPathResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetTesterMailBoxPathResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTesterMailBoxPathResult As String)
            MyBase.New
            Me.GetTesterMailBoxPathResult = GetTesterMailBoxPathResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTesterMailBoxPathWithPrefixRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTesterMailBoxPathWithPrefix", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.GetTesterMailBoxPathWithPrefixRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.GetTesterMailBoxPathWithPrefixRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTesterMailBoxPathWithPrefixRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public QRTester As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public testerNo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal QRTester As String, ByVal testerNo As String)
            MyBase.New
            Me.QRTester = QRTester
            Me.testerNo = testerNo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTesterMailBoxPathWithPrefixResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTesterMailBoxPathWithPrefixResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As FTService.GetTesterMailBoxPathWithPrefixResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FTService.GetTesterMailBoxPathWithPrefixResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTesterMailBoxPathWithPrefixResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetTesterMailBoxPathWithPrefixResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTesterMailBoxPathWithPrefixResult As String)
            MyBase.New
            Me.GetTesterMailBoxPathWithPrefixResult = GetTesterMailBoxPathWithPrefixResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SettingServiceSoapChannel
        Inherits FTService.SettingServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SettingServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of FTService.SettingServiceSoap)
        Implements FTService.SettingServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FTService_SettingServiceSoap_GetMailBoxPath(ByVal request As FTService.GetMailBoxPathRequest) As FTService.GetMailBoxPathResponse Implements FTService.SettingServiceSoap.GetMailBoxPath
            Return MyBase.Channel.GetMailBoxPath(request)
        End Function
        
        Public Function GetMailBoxPath(ByVal testerType As String) As String
            Dim inValue As FTService.GetMailBoxPathRequest = New FTService.GetMailBoxPathRequest()
            inValue.Body = New FTService.GetMailBoxPathRequestBody()
            inValue.Body.testerType = testerType
            Dim retVal As FTService.GetMailBoxPathResponse = CType(Me,FTService.SettingServiceSoap).GetMailBoxPath(inValue)
            Return retVal.Body.GetMailBoxPathResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FTService_SettingServiceSoap_GetTestFlowNo(ByVal request As FTService.GetTestFlowNoRequest) As FTService.GetTestFlowNoResponse Implements FTService.SettingServiceSoap.GetTestFlowNo
            Return MyBase.Channel.GetTestFlowNo(request)
        End Function
        
        Public Function GetTestFlowNo(ByVal flowName As String) As String
            Dim inValue As FTService.GetTestFlowNoRequest = New FTService.GetTestFlowNoRequest()
            inValue.Body = New FTService.GetTestFlowNoRequestBody()
            inValue.Body.flowName = flowName
            Dim retVal As FTService.GetTestFlowNoResponse = CType(Me,FTService.SettingServiceSoap).GetTestFlowNo(inValue)
            Return retVal.Body.GetTestFlowNoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FTService_SettingServiceSoap_LotRptIsIgnore(ByVal request As FTService.LotRptIsIgnoreRequest) As FTService.LotRptIsIgnoreResponse Implements FTService.SettingServiceSoap.LotRptIsIgnore
            Return MyBase.Channel.LotRptIsIgnore(request)
        End Function
        
        Public Function LotRptIsIgnore(ByVal errorNo As String) As Boolean
            Dim inValue As FTService.LotRptIsIgnoreRequest = New FTService.LotRptIsIgnoreRequest()
            inValue.Body = New FTService.LotRptIsIgnoreRequestBody()
            inValue.Body.errorNo = errorNo
            Dim retVal As FTService.LotRptIsIgnoreResponse = CType(Me,FTService.SettingServiceSoap).LotRptIsIgnore(inValue)
            Return retVal.Body.LotRptIsIgnoreResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FTService_SettingServiceSoap_GetTesterMailBoxPath(ByVal request As FTService.GetTesterMailBoxPathRequest) As FTService.GetTesterMailBoxPathResponse Implements FTService.SettingServiceSoap.GetTesterMailBoxPath
            Return MyBase.Channel.GetTesterMailBoxPath(request)
        End Function
        
        Public Function GetTesterMailBoxPath(ByVal testerType As String, ByVal testerNo As String) As String
            Dim inValue As FTService.GetTesterMailBoxPathRequest = New FTService.GetTesterMailBoxPathRequest()
            inValue.Body = New FTService.GetTesterMailBoxPathRequestBody()
            inValue.Body.testerType = testerType
            inValue.Body.testerNo = testerNo
            Dim retVal As FTService.GetTesterMailBoxPathResponse = CType(Me,FTService.SettingServiceSoap).GetTesterMailBoxPath(inValue)
            Return retVal.Body.GetTesterMailBoxPathResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FTService_SettingServiceSoap_GetTesterMailBoxPathWithPrefix(ByVal request As FTService.GetTesterMailBoxPathWithPrefixRequest) As FTService.GetTesterMailBoxPathWithPrefixResponse Implements FTService.SettingServiceSoap.GetTesterMailBoxPathWithPrefix
            Return MyBase.Channel.GetTesterMailBoxPathWithPrefix(request)
        End Function
        
        Public Function GetTesterMailBoxPathWithPrefix(ByVal QRTester As String, ByVal testerNo As String) As String
            Dim inValue As FTService.GetTesterMailBoxPathWithPrefixRequest = New FTService.GetTesterMailBoxPathWithPrefixRequest()
            inValue.Body = New FTService.GetTesterMailBoxPathWithPrefixRequestBody()
            inValue.Body.QRTester = QRTester
            inValue.Body.testerNo = testerNo
            Dim retVal As FTService.GetTesterMailBoxPathWithPrefixResponse = CType(Me,FTService.SettingServiceSoap).GetTesterMailBoxPathWithPrefix(inValue)
            Return retVal.Body.GetTesterMailBoxPathWithPrefixResult
        End Function
    End Class
End Namespace
